2021-05-28 05:20:49,180 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting env: {}
2021-05-28 05:20:49,180 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-28 05:20:49,180 INFO    MainThread:29752 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_052049-361wor0v/logs/debug.log
2021-05-28 05:20:49,180 INFO    MainThread:29752 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_052049-361wor0v/logs/debug-internal.log
2021-05-28 05:20:49,181 INFO    MainThread:29752 [wandb_init.py:init():369] calling init triggers
2021-05-28 05:20:49,181 INFO    MainThread:29752 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'img_size': 320, 'batch_size': 16, 'init_lr': 0.005896061335076594}
2021-05-28 05:20:49,181 INFO    MainThread:29752 [wandb_init.py:init():389] re-initializing run, found existing run on stack: sw3ialnt
2021-05-28 05:20:49,181 INFO    MainThread:29752 [wandb_run.py:finish():1208] finishing run seokjin/optuna/sw3ialnt
2021-05-28 05:20:49,181 INFO    MainThread:29752 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-28 05:20:49,181 INFO    MainThread:29752 [wandb_run.py:_restore():1507] restore
2021-05-28 05:20:51,410 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 05:20:52,096 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 4029
}

2021-05-28 05:20:52,504 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1368
  total_bytes: 4226
}

2021-05-28 05:20:52,606 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4029
  total_bytes: 4226
}

2021-05-28 05:20:52,708 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4226
  total_bytes: 4226
}

2021-05-28 05:20:52,809 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4226
  total_bytes: 4226
}

2021-05-28 05:20:52,911 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4226
  total_bytes: 4226
}

2021-05-28 05:20:53,013 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4226
  total_bytes: 4226
}

2021-05-28 05:20:53,115 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4226
  total_bytes: 4226
}

2021-05-28 05:20:53,217 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4226
  total_bytes: 4226
}

2021-05-28 05:20:53,318 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4226
  total_bytes: 4226
}

2021-05-28 05:20:54,412 INFO    MainThread:29752 [wandb_run.py:_show_summary():1812] rendering summary
2021-05-28 05:20:54,412 INFO    MainThread:29752 [wandb_run.py:_show_history():1850] rendering history
2021-05-28 05:20:54,412 INFO    MainThread:29752 [wandb_run.py:_show_files():1879] logging synced files
2021-05-28 05:20:54,414 INFO    MainThread:29752 [wandb_init.py:init():418] starting backend
2021-05-28 05:20:54,414 INFO    MainThread:29752 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-28 05:20:54,417 INFO    MainThread:29752 [backend.py:ensure_launched():132] starting backend process...
2021-05-28 05:20:54,460 INFO    MainThread:29752 [backend.py:ensure_launched():136] started backend process with pid: 30483
2021-05-28 05:20:54,462 INFO    MainThread:29752 [wandb_init.py:init():423] backend started and connected
2021-05-28 05:20:54,464 INFO    MainThread:29752 [wandb_init.py:init():465] updated telemetry
2021-05-28 05:20:54,464 INFO    MainThread:29752 [wandb_init.py:init():484] communicating current version
2021-05-28 05:20:55,274 INFO    MainThread:29752 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.31 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-28 05:20:55,274 INFO    MainThread:29752 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-28 05:20:55,490 INFO    MainThread:29752 [wandb_init.py:init():522] starting run threads in backend
2021-05-28 05:20:55,526 INFO    MainThread:29752 [wandb_run.py:_console_start():1565] atexit reg
2021-05-28 05:20:55,526 INFO    MainThread:29752 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-28 05:20:55,526 INFO    MainThread:29752 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-28 05:20:55,531 INFO    MainThread:29752 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-28 05:20:55,531 INFO    MainThread:29752 [wandb_init.py:init():546] run started, returning control to user process
2021-05-28 05:34:17,674 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting env: {}
2021-05-28 05:34:17,674 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-28 05:34:17,674 INFO    MainThread:29752 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_053417-1d5hfuv4/logs/debug.log
2021-05-28 05:34:17,674 INFO    MainThread:29752 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_053417-1d5hfuv4/logs/debug-internal.log
2021-05-28 05:34:17,674 INFO    MainThread:29752 [wandb_init.py:init():369] calling init triggers
2021-05-28 05:34:17,675 INFO    MainThread:29752 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'img_size': 288, 'batch_size': 16, 'init_lr': 0.0017182173154235848}
2021-05-28 05:34:17,675 INFO    MainThread:29752 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 361wor0v
2021-05-28 05:34:17,675 INFO    MainThread:29752 [wandb_run.py:finish():1208] finishing run seokjin/optuna/361wor0v
